### PR TITLE
adding newsletter checkboxes

### PR DESCRIPTION
**Pull request by kaylima**
Attempting to add multiple newsletter signup checkboxes to the homepage of wisconsinwatch.org per Help Scout ticket request #1392. http://wisconsinwatch.us4.list-manage.com/subscribe/post?u=91b0dfab9d494b66c92b76777&id=d7ab6931a6 used as a reference.

### CODE REVIEW

**Comment by kaylima** [comment]
@julia67 would love your guidance for this - esp. to make sure the hide/show incorporates the new checkboxes. thanks!

**Review by julia-smith — DISMISSED** [review]
The form changes look good! 

The show/hide piece needs to be edited here: https://github.com/INN/umbrella-wcij/blob/f7304645b60a8585a7141106bfc201db480c7235/wp-content/themes/wisconsinwatch/js/largo-child.js#L37-L46

And the list items need a little CSS love:

screen shot 2017-10-26 at 2 01 15 am

**Comment by benlk** [comment]
screen shot 2017-11-01 at 3 07 00 pm

Does this look okay?

**Comment by kaylima** [comment]
@ben please make the following changes: 
1. Change "New Story Alerts" to "New story alerts" (lower case for story and alerts).
2. Remove "Newsletters" from below "Last name".
3. Change to "Subscribe to our free newsletters" (plural).
4. Maybe give the elements some breathing room... space between "Subscribe to our.." and the email field, space above the Subscribe button, etc.

**Comment by benlk** [comment]
Fiddled around with the spacing some; made the button wider so the form wouldn't seem as lopsided.

screen shot 2017-11-01 at 6 14 26 pm

I'm not sure whether this needs less space between the checkboxes and button or more space between the input fields and the checkboxes.

**Comment by kaylima** [comment]
@benlk looks good to me! Let's get it on staging to test / share with wcij.

**Comment by benlk** [comment]
Status of this PR: I've deployed the related changes to staging, but they're not working on staging. They work in the local dev environment.

Any idea why this might be? I've cleared caches, added a cachebuster string to the file, and even run the exact same code from the file through the browser console successfully, but it doesn't work.

**Comment by benlk** [comment]
Updating the following plugins allowed this to work on staging:

- Akismet (now 4.0)
- Chartbeat (deactivated, now 2.0.7)
- Co-Authors Plus (now 3.2.2)
- Disqus (now 2.87)
- Presspoint (now 3.1)
- Redirection (now 2.9.1)
- Regenerate Thumbnails (deactivated, now 2.3.1)

Deployed to staging; sent to Wisconsin for review.

**Pull request merged**
